### ISSUE TITLE
Add date to reference email

### ISSUE THREAD

**Issue by Paulina-Rosetta** [TheRosettaFoundation/SOLAS-Match-Backend#46]
A volunteer has asked if the date could be added to the task information on the automatic volunteer reference email. Would this be a lot of work?

I guess either the date of when the task was claimed or submitted would be ok to include. He asked for the submission date, but whatever is easier...

**Comment by alanbarrett** [comment]
This is pretty easy to do. But I only can easily get access to the "Uploaded Time" for archived Tasks.

For un-archived Tasks, I would have to display either Task Deadline or Task Created time. I think Task Created time would be somewhat more accurate as the deadline might be in the future.

    Alan.

**Comment by Paulina-Rosetta** [comment]
That makes perfect sense. I agree that Task Created would be better.

**Comment by alanbarrett** [comment]
@Paulina-Rosetta  @stefania91 
This is now done. I will forward you and example of the output (faked, because I did not do these tasks).

These are the commits that resolve this...
commit f68422f3fc8299cd98ad57223e1dfeff25678201
commit a79925900007544e97b03871b84e537d97abb679
commit fc72da7ec83c3456fa1ba9cb635fc7fffe33c647

    Alan.
